Adjust make-release script for git.

diff --git a/admin/make-release b/admin/make-release
--- a/admin/make-release
+++ b/admin/make-release
@@ -3,30 +3,50 @@
 
 # Usage: make-release [branch]
 
-version=`python -c 'import phoupl; print phoupl.__version__' | tr -d '\n'`
+set -e
 
 repo=photo-uploader
 
-tmp=`mktemp -dt $repo-build-XXXXXX`
+version=`python -c 'import phoupl; print phoupl.__version__' | tr -d '\n'`
 
-cd $tmp
-echo Working in $tmp
+srcdir=`pwd`
+
+
+dotag=0
 if [ "x$1" = "xbranch" ] ; then
-    rel=RELEASE_`echo -n $version|tr . _`
-    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
-    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
-else
-    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
+    checkout=HEAD
+    dotag=1
+    # Pre release checks
+    if grep -q '^200[0-9]???? - ' ChangeLog ; then
+        echo 'ChangeLog does not seem to be finalised, aborting!'
+        exit 1
+    fi
+    shift
+elif [ "x$1" = "x" ] ; then
+    checkout=HEAD
+else 
+    checkout=$1
+    version=$1
+    shift
 fi
 
+tmp=`mktemp -dt $repo-build-XXXXXX`
+cd $tmp
+echo Working in $tmp
+echo "Creating release $version from $checkout"
+git clone $srcdir $repo-$version
 cd $repo-$version
 
 ./setup.py sdist --formats=gztar,bztar,zip
 
-if [ "x$1" = "xbranch" ] ; then
-    ./setup.py register
-fi
-
 mv dist/* ../
 
-echo "Release is in $tmp directory"
+if [ $dotag -eq 1 ] ; then
+    ./setup.py register
+    # Tag the release
+    git tag -s -m "Tag release $version" "$version"
+fi
+
+echo "Release is in $tmp directory:"
+ls -lh $tmp
+chmod 644 $tmp/$repo-$version.*
